name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Build
#         run: docker build .
#   unit_tests:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Run PHP unit tests
#         run: docker-compose run github-acitons-php ./vendor/bin/phpunit
    - name: Composer install
        uses: docker://composer:1.9.1
        with:
            args: install
    - name: PHPUnit testing
        uses: docker://php:5.5
        with:
            args: php vendor/bin/phpunit
