name: PHP Composer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setting up PHP
        uses: ./.github/actions/php

      - name: Installing Composer
        run: composer install --no-ansi --no-interaction --no-suggest --prefer-dist

      - name: Running PHPStan
        run: ./vendor/bin/phpstan analyse src tests --level 7

      - name: PHP Insights
        run: ./vendor/bin/phpinsights --no-interaction --min-quality=90 --min-complexity=90 --min-architecture=90 --min-style=90

      # - name: Running PHPUnit
      #   run: ./vendor/bin/phpunit --configuration phpunit.xml


      - name: PHPUnit tests
        uses: graychen/phpunit-action@v1.0.0
        #with:
        #  config: ./phpunit.xml

      # - name: Running PHPUnit
      #   uses: php-actions/phpunit@v1
      #   with:
      #     config: ./phpunit.xml
